[experiment]
project           = "CliMAgen.jl"
name              = "mnist_3d"
savedir           = "output"
rngseed           = 42
logging           = false
nogpu             = false

[data]
batchsize         = 16
resolution        = 64
ntime             = 16

[model]
inchannels        = 1
sigma_max         = 190.0
sigma_min         = 1e-2

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 250
freq_chckpt       = 10

[sampling]
nsteps            = 250
ngifs             = 3
nsamples          = 10
sampler           = "euler"
