[experiment]
project           = "CliMAgen.jl"
name              = "context2dturbulence"
savedir           = "output"
rngseed           = 123
logging           = true
nogpu             = false

[data]
batchsize         = 1
resolution        = 512
wavenumber        = 0
fraction          = 0.02
standard_scaling  = false

[model]
noised_channels   = 2
context_channels  = 1
sigma_max         = 1000.0
sigma_min         = 1e-2
dropout_p         = 0.0
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 1
freq_chckpt       = 80

[sampling]
nsteps            = 500
nsamples          = 10
nimages           = 10
sampler           = "euler"
tilesize          = 512
