[experiment]
project           = "CliMAgen.jl"
name              = "1dks"
savedir           = "output"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 64
standard_scaling  = false
fraction          = 0.1
n_pixels          = 128
n_time            = 128

[model]
inchannels        = 1
sigma_max         = 220.0
sigma_min         = 1e-2
dropout_p         = 0.0
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 250
freq_chckpt       = 260

[sampling]
make_samples      = true
samples_file      = "samples.hdf5"
nsteps            = 250
nsamples          = 200
nimages           = 10
sampler           = "euler"
k_bias            = 0
shift             = true
