env:
  JULIA_VERSION: "1.8.1"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  DATADEPS_ALWAYS_ACCEPT: true

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate status"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate status"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - label: "init :flower_playing_cards:"
    key: "init_gpu_env"
    command:
      - "export CUDA_HOME=/usr/local/cuda-$$CUDA_VERSION"

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile(;strict=true)'"

      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile(;strict=true)'"

      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"

      - "julia --project -e 'using Pkg; Pkg.status()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_cpus_per_task: 8
      slurm_gres: "gpu:1"
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --color=yes --check-bounds=yes --project test/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_mem: 64GB
      slurm_ntasks: 1

  - label: ":flower_playing_cards: unit tests"
    key: "gpu_unittests"
    command:
      - "export CUDA_HOME=/usr/local/cuda-$$CUDA_VERSION"
      - "julia --color=yes --check-bounds=yes --project test/runtests.jl CUDA"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - label: ":flower_playing_cards: MNIST"
    key: "gpu_mnist"
    command:
      - "export CUDA_HOME=/usr/local/cuda-$$CUDA_VERSION"
      - "julia --color=yes --check-bounds=yes --project=examples examples/mnist/train_diffusion.jl CUDA"
      
      - "julia --color=yes --check-bounds=yes --project=examples examples/mnist/sanity_checks_diffusion.jl CUDA"
    artifact_paths: "examples/mnist/output/*.jpeg"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"