[experiment]
project           = "CliMAgen.jl"
name              = "conus404_test"
savedir           = "output_precip_standard_scaling"
rngseed           = 123
logging           = true
nogpu             = false

[data]
batchsize         = 64
standard_scaling  = true
low_pass          = false
low_pass_k        = 8
n_pixels		  = 128

[model]
inchannels        = 2
dropout_p         = 0.0
sigma_max         = 305.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3
periodic          = false

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 150
freq_chckpt       = 50

[sampling]
nsteps            = 250
nsamples_analysis = 100
nsamples_generate = 100
nimages           = 25
sampler           = "euler"
samples_file      = "samples.hdf5"
