[experiment]
project           = "CliMAgen.jl"
name              = "conus404_test"
savedir           = "output_tmax_p_standard_scaling"
rngseed           = 123
logging           = true
nogpu             = false

[data]
batchsize         = 64
standard_scaling  = true
low_pass          = false
low_pass_k        = 8
n_pixels          = 128
fname_train       = "/central/groups/esm/zhaoyi/conus404/wy1980_1989_t2max_rainmean.hdf5"
fname_test        = "/central/groups/esm/zhaoyi/conus404/wy2010_2019_t2max_rainmean.hdf5"
precip_floor      = 1e-10
precip_channel    = 2

[model]
inchannels        = 2
dropout_p         = 0.0
sigma_max         = 325.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3
periodic          = false

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 200
freq_chckpt       = 50

[sampling]
nsteps            = 250
nsamples_analysis = 100
nsamples_generate = 100
nimages           = 25
sampler           = "euler"
samples_file      = "samples.hdf5"

[downscaling]
downscale_samples_file          = "coarse_res_downscale.hdf5"
coarse_res_data_file            = "nothing"
coarse_res_data_preprocess_file = "preprocess_base_lores.jld2"
nsamples                        = 512