[experiment]
project           = "CliMAgen.jl"
name              = "ludo"
rngseed           = 123
nogpu             = false
savedir           = "output"

[data]
batchsize         = 128
fraction          = 1.0

[model]
noised_channels   = 1
context_channels  = 2
sigma_max         = 60.0
sigma_min         = 1e-2
dropout_p         = 0.0
mean_bypass       = false
shift_input       = false
shift_output      = false
scale_mean_bypass = false
gnorm             = false
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3
periodic          = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 800
freq_chckpt       = 100

[sampling]
nsteps            = 250
nsamples          = 30
nimages           = 10
sample_channels   = 1
sampler           = "euler"
