[experiment]
project           = "CliMAgen.jl"
name              = "uniform_16_nonzero_means_all_mods_on"
savedir           = "/home/kdeck/output/uniform_16_nonzero_means_all_mods_on/"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 64
tilesize          = 16
ndata             = 200

[model]
inchannels        = 1
sigma_max         = 16.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 100
freq_chckpt       = 100

[sampling]
nsteps            = 1000
nsamples          = 100
nimages           = 20
sampler           = "euler"
tilesize          = 16