[experiment]
project           = "CliMAgen.jl"
name              = "uniform_32_nonzero_means_all_mods_off"
savedir           = "/home/kdeck/output/uniform_32_nonzero_means_all_mods_off/"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 64
tilesize          = 32
ndata             = 200

[model]
inchannels        = 1
sigma_max         = 32.0
sigma_min         = 1e-2
mean_bypass       = false
shift_input       = false
shift_output      = false
scale_mean_bypass = false
gnorm             = false

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 100
freq_chckpt       = 100

[sampling]
nsteps            = 1000
nsamples          = 100
nimages           = 20
sampler           = "euler"
tilesize          = 32