[experiment]
project           = "CliMAgen.jl"
name              = "1dcorrelated_ou"
savedir           = "output"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 64
standard_scaling  = false
fraction          = 1.0
n_pixels          = 64
n_time            = 64

[model]
inchannels        = 1
sigma_max         = 115.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 100
freq_chckpt       = 80

[sampling]
nsteps            = 250
nsamples          = 100
nimages           = 25
sampler           = "euler"
