[experiment]
project           = "CliMAgen.jl"
name              = "speedy_weather"
savedir           = "output"
rngseed           = 123
nogpu             = false

[data]
batchsize         = 64
n_pixels_lat      = 96
n_pixels_lon      = 48

[model]
inchannels        = 1
sigma_max         = 50.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
freq_chckpt       = 1