[experiment]
project           = "CliMAgen.jl"
name              = "idealized_ocean"
savedir           = "output"
rngseed           = 123
logging           = true
nogpu             = false

[data]
batchsize         = 128
train_fraction    = 0.9
i_init            = 100
i_end             = 355
j_init            = 80
j_end             = 335

[model]
noised_channels   = 1
sigma_max         = 500.0
sigma_min         = 1e-2
dropout_p         = 0.0
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 10
freq_chckpt       = 100

[sampling]
nsteps            = 150
nsamples          = 100
nimages           = 10
sample_channels   = 1
sampler           = "euler"
tilesize          = 256