[experiment]
project           = "CliMAgen.jl"
name              = "response2dturb"
rngseed           = 123
logging           = true
nogpu             = false
savedir           = "output_32x32_strong_transform"

[data]
batchsize         = 128
resolution        = 32
fraction          = 1.0
standard_scaling  = false
transform         = true
nonlinearity      = "strong"

[model]
noised_channels   = 2
sigma_max         = 66.0
sigma_min         = 1e-2
dropout_p         = 0.0
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true
proj_kernelsize   = 3
outer_kernelsize  = 3
middle_kernelsize = 3
inner_kernelsize  = 3
periodic          = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 200
freq_chckpt       = 100

[sampling]
nsteps            = 250
nsamples          = 100
nimages           = 10
sample_channels   = 2
sampler           = "euler"