[experiment]
project           = "CliMAgen.jl"
name              = "2dturbulence_test"
savedir           = "output"
rngseed           = 123
logging           = false
nogpu             = false

[data]
batchsize         = 64
tilesize          = 32
kernel_std        = 0
standard_scaling  = true
bias_amplitude    = 0
bias_wn           = 0

[model]
inchannels        = 2
sigma_max         = 90.0
sigma_min         = 1e-2
mean_bypass       = true
shift_input       = true
shift_output      = true
scale_mean_bypass = true
gnorm             = true

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 10
freq_chckpt       = 80

[sampling]
nsteps            = 1000
nsamples          = 10
nimages           = 10
sampler           = "euler"
tilesize          = 32
