[experiment]
project           = "CliMAgen.jl"
name              = "2dturbulence_test"
savedir           = "output"
rngseed           = 123
logging           = true
nogpu             = false

[data]
batchsize         = 64
tilesize          = 128

[model]
inchannels        = 2
sigma_max         = 90.0
sigma_min         = 1e-2
mean_bypass       = false
shift_input       = false
shift_output      = false
scale_mean_bypass = false

[optimizer]
learning_rate     = 2e-4
epsilon           = 1e-8
beta_1            = 0.9
beta_2            = 0.999
gradnorm          = 1.0
ema_rate          = 0.999
nwarmup           = 5000

[training]
nepochs           = 240
freq_chckpt       = 80

[sampling]
nsteps            = 1000
nsamples          = 100
nimages           = 25
sampler           = "euler"
tilesize          = 128
